
package me.frenz.day07;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class Day07Test {

    final List<String> input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """.lines().toList();

    @Test
    void testExampleA() {
        assertEquals(21, new Day07(input).part1());
        assertEquals(1, new Day07(List.of(".S.", ".^.", "...")).part1());
    }

    @Test
    void testExampleB() {
        assertEquals(40, new Day07(input).part2());
    }
}
